### ISSUE TITLE
Can’t choose date and can’t return keyboard.

### ISSUE THREAD

**Issue by HawkeyNL** [vanwijkdave/Counted#1]
I am able to choose a month, but no day. The days are listed in 3/4 dots. ‘....’! 

When typing in a subject I can’t return the keyboard. I’m able to close my keyboard when going back to the tweak list.

Info:
iPhone XR
Uncover 4.3.1
iOS 13.3

**Comment by Evolve0-Polygon8** [comment]
I’m having the same problem on iOS 13.3 iPhone 6s Uncover.

**Comment by fgegner** [comment]
I can select the date, but the done button does not work and that field remains blank.   Sometimes the option to select the date doesn’t open, just tap and nothing, repeat and nothing. 

iPhone X
iOS 13.3.1
cydia64_1.1.33
Checkra1n 0.10.1

**Comment by BryanNak** [comment]
I’m also having the same problem where i can choose my month and year but no specific day.

Info:
iPhone XS
iOS 13.3
Unc0ver 4.3.1

**Comment by vanwijkdave** [comment]
Have you got any tweak installed that affects the settings?

**Comment by Evolve0-Polygon8** [comment]
> Have you got any tweak installed that affects the settings?

Oh yep that was the issue. I removed BetterSettings and it worked.

**Comment by vanwijkdave** [comment]
> Oh yep that was the issue. I removed BetterSettings and it worked.
Awesome :)
