### ISSUE TITLE
Text changes back to date when clock time changes

### ISSUE THREAD

**Issue by Scarsz** [vanwijkdave/Counted#3]
You can press the time to toggle over to the Counted text, but the text resets back to the date when the clock time changes.

iPhone 11, 13.3, unc0ver.

**Comment by vanwijkdave** [comment]
This is done on purpose, because some might forget to un-toggle it ☺️

**Comment by Scarsz** [comment]
That... doesn't sound like a good thing. I'd at least hope for that to be toggleable. What originally inspired me to make this issue is that I toggled to the Counted text and not even a second later it disappeared. That's not a very good UX.
