### ISSUE TITLE
Drains battery

### ISSUE THREAD

**Issue by deafwired** [vanwijkdave/Counted#7]
On ios 13.5 on my iphone xs, i have it replace the swipe bar, the thing is, whenever my phone turns on, it wont turn off, i think being able to chose how many times it shows up or figure out why it wont turn off the screen, even in low power mode

**Comment by vanwijkdave** [comment]
Sorry, what do you mean? I just replace the text, I don’t add anything power hungry

**Comment by deafwired** [comment]
Sorry, i think something was wrong with one of my tweaks, my lock screen wouldn't turn off, so i had guessed it was this tweak, turns out it isn't, and i had to restore my rootfs so it doesn't seem to be happening anymore. Tldr: wasnt your tweak

**Comment by vanwijkdave** [comment]
Issues closed: non-issue
